	.ORG	0X0000
    JMP	INICIO
frase:.DB "SISTEMA EN ESTADO OPERATIVO",13,10,"SI DESEA MODIFICAR LOS PARAMETROS DE AVISO Y ALARMA, PRESIONE:",13,10,"¡LOS DATOS DEBEN SER INGRESADOS EN ESE ORDEN!",13,10,"C = CONCENTRACION DE CO2",13,10,"G = CONCENTRACION DE GASES INFLAMABLES",13,10,"P = PARTICULAS EN SUSPENCION",13,10,"T = TEMPERATURA AMBIENTE (INGRESE PRIMERO SUPERIOR Y DESPUES INFERIOR)",13,10,"H = HUMEDAD RELATIVA",13,10
INICIO:
;CONFIGURACION DE PUNTERO DE PILA
    LDI	R16,HIGH(RAMEND)
    OUT	SPH,R16
    LDI	R16,LOW(RAMEND)
    OUT	SPL,R16
;CONFIGURACION DE PUERTOS ENTRADA SALIDA
    LDI	R16,(1<<PORTD0)|(1<<PORTD1)|(1<<PORTD2)|(1<<PORTD3)|(1<<PORTD4)|(1<<PORTD5)|(1<<PORTD6)|(1<<PORTD7);PUERTOS DE SALIDA, TODOS LOS D
    OUT	DDRD,R16
    LDI R16,(1<<PORTB0)|(1<<PORTB1)|(1<<PORTB2)|(1<<PORTB3);PUERTOS DE SALIDA, 0,1,2,3 DE B
    OUT DDRB,R16
    SBI	PORTB,PORTB7;ACTIVACION RESISTENCIA PULL UP DE EL PULSADOR EN EL PUERTO 7 DE B 
;CONFIGURACION DE USART
    LDI   R16,0;VELOCIDAD NORMAL DE USART
    STS   UCSR0A,R16
    LDI   R16,(1<<RXCE0)|(1<<TXEN0)|(1<<RXEN0);ACTIVACION DE INTERRUPCION DE RECEPCION COMPLETA, TRASMISION Y RECEPCION 
    STS   UCSR0B,R16
    LDI   R16,(1<<UCSZ00)|(1<<UCSZ01);LONGITUD DE DATO 8 BITS
    STS   UCSR0C,R16
	LDI   R16,103;VELOCIDAD DE COMUNICACION DE 9000BPS
    STS   UBRR0L,R16
    LDI   R16,0
    STS   UBRR0H,R16 
;PALABRA
    LDI   ZH,HIGH(2*FRASE)
    LDI   ZL,LOW(2*FRASE)
    LDI   R17,320
REPETIDOR:
    LPM   R16,Z+
    STS   UDR0,R16
ESPERAR:
    LDS   R16,UCSR0A
    SBRS  R16,UDRE0
    RJMP  ESPERAR
    DEC   R17
    BRNE  REPETIDOR
    
;CONFIGURACION ADC
    LDI	R16,(1<<REFS0)
    STS	ADMUX,R16
    LDI R16, (1<<ADEN)|(1<<ADSC)|(1<<ADIE)|(1<<ADATE)|(1<<ADPS2)|(1<<ADPS1)
    STS	ADCSRA,R16
    LDI	R16,(1<<ADTS1)
    STS	ADCSRB,R16
    LDI	R16,(1<<ADC0D)
    STS	DIDR0,R16
;FIN CONFIGURACION ADC
    LDI	R16,(1<<ISC01)|(1<<ISC00)
    STS	EICRA,R16
    SEI
VOLVER:
    RJMP VOLVER


